spring.application.name=spring-security-demo

spring.datasource.url=jdbc:postgresql://localhost:5432/spring-security-demo
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.security.user.name=richard1
spring.security.user.password=admin

server.servlet.session.cookie.same-site=strict

